### PR TITLE
YAML Logo size changed

### PR DESCRIPTION
**Pull request by Pakeetharan**
Issue #76 : Logo size Increased to 48px to match the other logos

### CODE REVIEW

**Comment by Pakeetharan** [comment]
Kindly mention why you are rejecting a PR next time.

**Comment by YoshithaRathnayake** [comment]
> Kindly mention why you are rejecting a PR next time.

Because you didn't ask me to do this pr you should ask me if you are doing this or not @Pakeetharan

**Comment by Pakeetharan** [comment]
> > Kindly mention why you are rejecting a PR next time.
> 
> Because you didn't ask me to do this pr you should ask me if you are doing this or not @Pakeetharan

There were no proper instructions given such that one have to get your permission before completing an issue. Mention only the assignee can complete the task in your issues if you are going to mark a PR spam or invalid 👎  It's our mistake that we didn't see your profile before making a PR

**Comment by YoshithaRathnayake** [comment]
> > > Kindly mention why you are rejecting a PR next time.
> > 
> > 
> > Because you didn't ask me to do this pr you should ask me if you are doing this or not @Pakeetharan
> 
> There were no proper instructions given such that one have to get your permission before completing an issue. Mention only the assignee can complete the task in your issues if you are going to mark a PR spam or invalid 👎 It's our mistake that we didn't see your profile before making a PR

No every one have a good habit to ask to assign it to him @Pakeetharan

**Comment by YoshithaRathnayake** [comment]
> > > Kindly mention why you are rejecting a PR next time.
> > 
> > 
> > Because you didn't ask me to do this pr you should ask me if you are doing this or not @Pakeetharan
> 
> There were no proper instructions given such that one have to get your permission before completing an issue. Mention only the assignee can complete the task in your issues if you are going to mark a PR spam or invalid 👎 It's our mistake that we didn't see your profile before making a PR

Asking means asking to assign @Pakeetharan

**Comment by YoshithaRathnayake** [comment]
I will add spam bcs I don't know the people who have put PRs unexpectedly. I don't know about you, if you add a spam code. If there is a spam code my website get crashed therefore I put spam @Pakeetharan

**Comment by YoshithaRathnayake** [comment]
I will definitely put spam for the people like you. Why can't the people like you to ask to work on this and do this. People like you are the people who eat this whole world @Pakeetharan

**Pull request closed without merging**
